export default function stations() {
  return {
    at: '2023-08-16T00:16:42.889Z',
    stations: [
      {
        id: 3005,
        name: 'Welcome Park, NPS',
        coordinates: [-75.14403, 39.94733],
        totalDocks: 13,
        docksAvailable: 4,
        bikesAvailable: 7,
        classicBikesAvailable: 1,
        smartBikesAvailable: 0,
        electricBikesAvailable: 6,
        rewardBikesAvailable: 7,
        rewardDocksAvailable: 4,
        kioskStatus: 'FullService',
        kioskPublicStatus: 'Active',
        kioskConnectionStatus: 'Active',
        kioskType: 1,
        addressStreet: '191 S. 2nd St.',
        addressCity: 'Philadelphia',
        addressState: 'PA',
        addressZipCode: '19106',
        bikes: [
          {
            dockNumber: 1,
            isElectric: true,
            isAvailable: true,
            battery: 78,
          },
          {
            dockNumber: 4,
            isElectric: true,
            isAvailable: true,
            battery: 64,
          },
          {
            dockNumber: 7,
            isElectric: true,
            isAvailable: true,
            battery: 49,
          },
          {
            dockNumber: 8,
            isElectric: true,
            isAvailable: true,
            battery: 0,
          },
          {
            dockNumber: 9,
            isElectric: false,
            isAvailable: true,
            battery: null,
          },
          {
            dockNumber: 10,
            isElectric: true,
            isAvailable: true,
            battery: 21,
          },
          {
            dockNumber: 11,
            isElectric: true,
            isAvailable: true,
            battery: 58,
          },
          {
            dockNumber: 12,
            isElectric: false,
            isAvailable: false,
            battery: null,
          },
          {
            dockNumber: 13,
            isElectric: true,
            isAvailable: false,
            battery: 66,
          },
        ],
        closeTime: null,
        eventEnd: null,
        eventStart: null,
        isEventBased: false,
        isVirtual: false,
        kioskId: 3005,
        notes: null,
        openTime: null,
        publicText: '',
        timeZone: null,
        trikesAvailable: 0,
        latitude: 39.94733,
        longitude: -75.14403,
      },
    ],
    weather: {
      coord: {
        lon: -75.1638,
        lat: 39.9523,
      },
      weather: [
        {
          id: 803,
          main: 'Clouds',
          description: 'broken clouds',
          icon: '04n',
        },
      ],
      base: 'stations',
      main: {
        temp: 299.15,
        feels_like: 299.15,
        temp_min: 296.77,
        temp_max: 301.09,
        pressure: 1007,
        humidity: 79,
      },
      visibility: 10000,
      wind: {
        speed: 1.54,
        deg: 0,
      },
      clouds: {
        all: 75,
      },
      dt: 1692144364,
      sys: {
        type: 2,
        id: 2037403,
        country: 'US',
        sunrise: 1692094332,
        sunset: 1692143904,
      },
      timezone: -14400,
      id: 4560349,
      name: 'Philadelphia',
      cod: 200,
    },
  };
}
